server:
  port: 5001

spring:
  application:
    name: job-service

  config:
    import: "optional:configserver:"     # use service id
    #import: "optional:configserver:http://localhost:8888"   #  use localhost


  # Use the Config Server name registered in Eureka instead of localhost.
  cloud:
    config:
      discovery:
        enabled: true   #Enable discovery to find Config Server via Eureka.
        service-id: config-server
      name: datasource-db,spring-mvc,kafka,timezone    # Import required config file



  #database
  datasource:
    #url: "jdbc:mysql://localhost:2002/job_service"
    url: "jdbc:mysql://job-db:3306/job_service"   #using docker container
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: jobservice


#Eureka
eureka:
  instance:
    prefer-ip-address: true   # Use IP address instead of hostname
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
     #defaultZone: http://localhost:8762/eureka/   # register on Eureka
      defaultZone: http://eureka-server:8762/eureka/   # using docker

