server:
  port: ${PORT:5001}

spring:
  application:
    name: job-service

  config:
    import: optional:configserver:http://config-server:8888    # use service id
    #import: "optional:configserver:http://localhost:8888"   #  use localhost


  # Use the Config Server name registered in Eureka instead of localhost.
  cloud:
    config:
      name: datasource-db,spring-mvc,kafka,timezone    # Import required config file



  #database
  datasource:
    #url: "jdbc:mysql://localhost:2002/job_service"
    url: "jdbc:mysql://job-db:3306/job_service"   #using docker container
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${JOB_DB_USERNAME}
    password: ${JOB_DB_PASSWORD}
