server:
  port: ${PORT:5005}

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://config-server:8888
    # optional: prevent crash if config server unavailable

  cloud:
    config:
      name: mail,kafka

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8


logging:
  level:
    com.tihuz.notification_service: DEBUG
    org.springframework.kafka: INFO