server:
  port: ${PORT:5005}

spring:
  application:
    name: notification-service

  config:
    import: "optional:configserver:"
    # optional: prevent crash if config server unavailable

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://config-server:8888
      name: mail,kafka

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-server:8762/eureka/

logging:
  level:
    com.tihuz.notification_service: DEBUG
    org.springframework.kafka: INFO