server:
  port: ${PORT:5002}

spring:
  application:
    name: application-service

  config:
    import: optional:configserver:http://config-server:8888
   #import: "optional:configserver:http://localhost:8888"   #   use localhost


  #config-server
  cloud:
    config:
      name: spring-mvc,datasource-db,kafka,timezone

    openfeign:
      circuitbreaker:
        enabled: true

  #database
  datasource:
    #url: "jdbc:mysql://localhost:2003/application_service"
    url: "jdbc:mysql://application-db:3306/application_service"     #using docker container
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${APPLICATION_DB_USERNAME}
    password: ${APPLICATION_DB_PASSWORD}



#fallback
resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        sliding-window-size: 6
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 1

      JOB-SERVICE:
        sliding-window-size: 6
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 1

  timelimiter:
    instances:
      USER-SERVICE:
        timeout-duration: 3s
      JOB-SERVICE:
        timeout-duration: 3s


#cloudinary
#cloudinary:
#  cloud-name: dd1kwmoqe
#  api-key: 685652358234613
#  api-secret: ng1k-z6fiHScvtSU2sEUZZdcWpw
