 version: '3.9'

 services:

  # =========================
  # EUREKA
  # =========================
  eureka-server:
    container_name: eureka-server
    build: ./discovery-service
    ports:
      - "8762:8762"
    networks:
      - recruitment-network

  # =========================
  # CONFIG SERVER
  # =========================
  config-server:
    container_name: config-server
    build: ./config-server

    ports:
      - "8888:8888"

    environment:
      SERVER_PORT: 8888
      CONFIG_PROFILE: native
      EUREKA_SERVER_URL: http://eureka-server:8762/eureka/
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_VALID_DURATION: ${JWT_VALID_DURATION}
      JWT_REFRESH_DURATION: ${JWT_REFRESH_DURATION}
    

    depends_on:
      eureka-server:
        condition: service_started

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - recruitment-network
    
    volumes:
      - ./logs:/app/logs
      - ./config-server/src/main/resources/shared:/app/config/shared

  # =========================
  # ZIPKIN
  # =========================
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - recruitment-network



    # =========================
    # Zookeeper
    # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0                #Sử dụng image Zookeeper của Confluent.
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181                     #Cổng mà Zookeeper sẽ lắng nghe cho các kết nối từ Kafka và các client khác.            
      ZOOKEEPER_TICK_TIME: 2000                #Khoảng thời gian (tính bằng ms) mà Zookeeper sử dụng để kiểm tra kết nối và thực hiện các tác vụ nội bộ.  
    ports:
      - "2181:2181"                             # Map cổng 2181 của container Zookeeper ra cổng 2181 trên máy chủ để cho phép các dịch vụ khác kết nối đến Zookeeper.                                         
    networks:                  
      - recruitment-network


    # =========================
    # KAFKA
    # =========================

  kafka:
    restart: always
    image: confluentinc/cp-kafka:7.4.0            #Kafka image của Confluent
    container_name: kafka
    depends_on:                                   #Đảm bảo rằng Zookeeper đã khởi động trước khi Kafka bắt đầu khởi động, vì Kafka cần Zookeeper để quản lý cluster và lưu trữ metadata.
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1                          #Định danh duy nhất cho broker Kafka này trong cluster. Nếu bạn có nhiều broker, mỗi broker cần có một ID khác nhau.        
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181     #Địa chỉ kết nối đến Zookeeper, cho phép Kafka đăng ký và lấy thông tin về cluster.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092    #Địa chỉ mà các client dùng để kết nối tới kafka. Sử dụng localhost nếu bạn chạy Kafka trên máy cục bộ, hoặc sử dụng địa chỉ IP hoặc hostname nếu bạn chạy Kafka trong môi trường mạng.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
    ports:
      - "9092:9092"
      - "9093:9093"

    networks:                 
      - recruitment-network

  # kafka:
  #   image: confluentinc/cp-kafka:7.4.0
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   networks:                  
  #     - recruitment-network




  # =========================
  # REDIS
  # =========================
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    networks:
      - recruitment-network




  # =========================
  # MYSQL USER
  # =========================
  user-db:
    container_name: user-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_ROOT_PASSWORD}
      MYSQL_DATABASE: user_service
    ports:
      - "2001:3306"
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
      - recruitment-network

  # =========================
  # MYSQL JOB
  # =========================
  job-db:
    container_name: job-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_JOB_ROOT_PASSWORD}
      MYSQL_DATABASE: job_service
    ports:
      - "2002:3306"
    volumes:
      - job_db_data:/var/lib/mysql
    networks:
      - recruitment-network

  # =========================
  # MYSQL APPLICATION
  # =========================
  application-db:
    container_name: application-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_APPLICATION_ROOT_PASSWORD}
      MYSQL_DATABASE: application_service
    ports:
      - "2003:3306"
    volumes:
      - application_db_data:/var/lib/mysql
    networks:
      - recruitment-network


   # =========================
  # MYSQL COMPANY
  # =========================
  company-db:
    container_name: company-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_COMPANY_ROOT_PASSWORD}
      MYSQL_DATABASE: company_service
    ports:
      - "2004:3306"
    volumes:
      - company_db_data:/var/lib/mysql
    networks:
      - recruitment-network


    # =========================
  # MINIO SERVICE
    # =========================
  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    volumes:
      - minio_data:/data
    networks:
      - recruitment-network





  # =========================
  # USER SERVICE
  # =========================
  user-service:
    restart: always
    container_name: user-service
    build: ./user-service
    ports:
      - "5000:5000"

    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_DB_USERNAME: ${USER_DB_USERNAME}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      user-db:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network

    volumes:
    - ./logs:/app/logs

  # =========================
  # JOB SERVICE 
  # =========================
  job-service:
    restart: always
    container_name: job-service
    build: ./job-service
    ports:
      - "5001:5001"

    environment:
      JOB_DB_USERNAME: ${JOB_DB_USERNAME}
      JOB_DB_PASSWORD: ${JOB_DB_PASSWORD}

    depends_on:
      job-db:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network

    volumes:
    - ./logs:/app/logs

  # =========================
  # APPLICATION SERVICE
  # =========================
  application-service:
    restart: always
    container_name: application-service
    build: ./application-service
    ports:
      - "5002:5002"

    environment:
      APPLICATION_DB_USERNAME: ${APPLICATION_DB_USERNAME}
      APPLICATION_DB_PASSWORD: ${APPLICATION_DB_PASSWORD}
    
    depends_on:
      application-db:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network
    
    volumes:
    - ./logs:/app/logs


  # =========================
  # COMPANY SERVICE
  # =========================
  company-service:
    restart: always
    container_name: company-service
    build: ./company-service
    ports:
      - "5003:5003"

    environment:
      COMPANY_DB_USERNAME: ${COMPANY_DB_USERNAME}
      COMPANY_DB_PASSWORD: ${COMPANY_DB_PASSWORD}

    depends_on:
      company-db:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network
    
    volumes:
    - ./logs:/app/logs


 # =========================
  # MEDIA SERVICE
  # =========================
  media-service:
    restart: always
    container_name: media-service
    build: ./media-service
    ports:
      - "5004:5004"

    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}

    depends_on:
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network


   #NOTIFICATION-SERVICE
  notification-service:
    restart: always
    container_name: notification-service
    build: ./notification-service
    ports:
      - "5005:5005"
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8762/eureka/
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - recruitment-network
    volumes:
      - ./logs:/app/logs



  # =========================
  # GATEWAY
  # =========================
  api-gateway:
    restart: always
    container_name: api-gateway
    build: ./gateway-service
    ports:
      - "1111:1111"

    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - recruitment-network

    volumes:
    - ./logs:/app/logs
    


  # =========================
  # NGINX
  # =========================
  nginx:
    image: nginx:alpine
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    depends_on:
      - api-gateway

    restart: always

    networks:
      - recruitment-network


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://nginx:80
    depends_on:
      - nginx
    networks:
      - recruitment-network 



 networks:
  recruitment-network:
    driver: bridge

 volumes:
  user_db_data:
  job_db_data:
  application_db_data:
  company_db_data:
  minio_data: