spring:
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      bootstrap-servers: kafka:9092
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

        spring.json.type.mapping:
          companyEvent: com.tihuz.common.event.CompanyEvent
          jobEvent: com.tihuz.common.event.JobEvent
          userEvent: com.tihuz.common.event.UserEvent
          applicationStatusEvent: com.tihuz.common.event.ApplicationStatusEvent
          passwordResetEvent: com.tihuz.common.event.PasswordResetEvent

    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer