#redis
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8   # Maximum number of concurrent connections
          max-idle: 8     # Maximum number of idle connections to keep
          min-idle: 0     # Minimum number of idle connections.
