server:
  port: ${SERVER_PORT:5003}

spring:
  application:
    name: company-service

  config:
    import: optional:configserver:http://config-server:8888      # use service id
    #import: "optional:configserver:http://localhost:8888"   #  use localhost


  # Use the Config Server name registered in Eureka instead of localhost.
  cloud:
    config:
      name: datasource-db,spring-mvc,kafka,timezone    # Import required config file




#databae
  datasource:
    url: jdbc:mysql://company-db:3306/company_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${COMPANY_DB_USERNAME}
    password: ${COMPANY_DB_PASSWORD}

