server:
  port: ${SERVER_PORT:5004}

spring:
  application:
    name: media-service

  config:
    import: "optional:configserver:"   # call config server
    # optional: Do not crash the application immediately if the Config Server is unavailable.
    # configserver: Predefined prefix in Spring Boot.

  cloud:
    config:
      discovery:
        enabled: true   #Enable discovery to find Config Server in Eureka.
        service-id: config-server

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

# Eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-server:8762/eureka/