server:
  port: ${PORT:5000}

spring:
  application:
    name: user-service

  config:
    #import: "optional:configserver"   # call config server in eruka
    # optional: Do not crash the application immediately if the Config Server is unavailable.
    # configserver: Predefined prefix in Spring Boot.
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      name: datasource-db,spring-mvc,kafka,timezone,redis    # Import required config file


  #database
  datasource:
    url: jdbc:mysql://${USER_DB_HOST}:${USER_DB_PORT}/user_service
    #url: jdbc:mysql://user-db:3306/user_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}

