server:
  port: 5000

spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:"   # call config server
    # optional: Do not crash the application immediately if the Config Server is unavailable.
    # configserver: Predefined prefix in Spring Boot.

  cloud:
    config:
      discovery:
        enabled: true   #Enable discovery to find Config Server in Eureka.
        service-id: config-server
      name: datasource-db,spring-mvc,kafka,timezone    # Import required config file



  #database
  datasource:
    #url: "jdbc:mysql://localhost:2001/user_service"     #using local
    url: jdbc:mysql://user-db:3306/user_service     # using docker container
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: userservice

#Eureka
eureka:
  instance:
    prefer-ip-address: true   # Use IP address instead of hostname
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      #defaultZone: http://localhost:8762/eureka/   # register on Eureka
      defaultZone: http://eureka-server:8762/eureka/ # using Docker



