server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server

  profiles:   #It defines how the Config Server loads configuration.
    active: ${CONFIG_PROFILE:native} #native (local: File in the project or on the local disk.)
                  #git (Git repository: GitHub, GitLab...)

  #config server - native
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/shared # Common configuration files directory (src/main/resources/shared) # config sẽ được đọc trong file jar
          search-locations: file:/app/config/shared  # config lưu vào config/shared (thư mục trong docker) chứ ko lưu trong jar nhưng vẫn build lại image ( nếu có volume thì chỉ cần restart)

        overrides:
          jwt.signerKey: ${JWT_SIGNER_KEY}
          jwt.valid-duration: ${JWT_VALID_DURATION}
          jwt.refreshable-duration: ${JWT_REFRESH_DURATION}

