server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server

  profiles:   #It defines how the Config Server loads configuration.
    active: ${CONFIG_PROFILE:native} #native (local: File in the project or on the local disk.)
                  #git (Git repository: GitHub, GitLab...)

  #config server - native
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/shared # Common configuration files directory (src/main/resources/shared)
          search-locations: file:/app/config/shared


        overrides:
          jwt.signerKey: ${JWT_SIGNER_KEY}
          jwt.valid-duration: ${JWT_VALID_DURATION}
          jwt.refreshable-duration: ${JWT_REFRESH_DURATION}

#Eureka
eureka:
  instance:
    prefer-ip-address: true   # Use IP address instead of hostname
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      #defaultZone: http://localhost:8762/eureka/   # register on Eureka
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8762/eureka/}  # using Docker containers