name: Deploy TizJob

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check server
        run: |
          echo "Running on Ubuntu production server"
          whoami
          hostname
          docker --version
          docker compose version